/**
 * C-header emitter. Emits only — it never parses `.h`.
 *
 * Rules (see project prompt):
 *  - uintN -> uintN_t, intN -> intN_t, float32 -> float, float64 -> double
 *  - bytes/padding -> uint8_t x[N]; char[N] -> char x[N]
 *  - inline structs -> typedef struct <Parent>_<field>
 *  - reusable structs -> top-level typedefs in dependency order
 *  - enum fields -> typedef enum with UPPER_SNAKE constants, prefixed by the enclosing type
 *  - bits -> bitfield struct; widths must sum to <= container size
 *  - #pragma pack from design.packing; optional _Static_assert on sizeof
 */

import { Design, Field, LayoutResult } from './types';
import { toUpperSnake, sanitizeIdentifier } from './identifiers';
import { computeLayout, layoutFieldList } from './layout';
import { emitLayoutDoc } from './emitLayoutDoc';
import { parseType, scalarInfo } from './typeUtil';

export interface HeaderOptions {
  sourceFileName?: string;
  staticAssert?: boolean;
  includeStyle?: 'angle' | 'quote';
  /** declare enum fields with the generated enum typedef instead of their int type */
  enumTypedefForFields?: boolean;
  /** MAX capacity for array.countField members (0 / undefined -> FAM if last, else warn) */
  arrayMax?: number;
}

export interface HeaderResult {
  header: string;
  layoutDoc: string;
  warnings: string[];
}

export function generateHeader(design: Design, opts: HeaderOptions = {}): HeaderResult {
  const warnings: string[] = [];
  const packing = design.packing ?? 1;
  const guard = `${toUpperSnake(design.name)}_H`;
  const src = opts.sourceFileName ?? `${design.name}.design.json`;
  const include = opts.includeStyle === 'quote' ? '"stdint.h"' : '<stdint.h>';

  const out: string[] = [];
  out.push(`/* Generated by Binary File Designer — do not edit. Regenerate from ${src}. */`);
  out.push(`#ifndef ${guard}`);
  out.push(`#define ${guard}`);
  out.push('');
  out.push(`#include ${include}`);
  out.push('');
  if (packing !== false) {
    out.push(`#pragma pack(push, ${packing})          /* from design.packing */`);
    out.push('');
  } else {
    out.push('/* packing disabled — natural (compiler-default) alignment, no #pragma pack */');
    out.push('');
  }

  // ---- reusable structs, dependency order ----
  const order = topoSortStructs(design);
  for (const structName of order) {
    const def = design.structs![structName];
    const preludes: string[] = [];
    const body = emitStructBody(design, def.fields, structName, opts, warnings, preludes);
    for (const p of preludes) {
      out.push(p);
      out.push('');
    }
    out.push(`typedef struct ${structName} {`);
    out.push(...body);
    out.push(`} ${structName};`);
    out.push('');
  }

  // ---- top-level struct (+ its enum/bit/inline preludes) ----
  const topPreludes: string[] = [];
  const topBody = emitStructBody(design, design.fields ?? [], design.name, opts, warnings, topPreludes);
  for (const p of topPreludes) {
    out.push(p);
    out.push('');
  }
  out.push(`typedef struct ${design.name} {`);
  out.push(...topBody);
  out.push(`} ${design.name};`);
  out.push('');

  if (packing !== false) {
    out.push('#pragma pack(pop)');
    out.push('');
  }

  if (opts.staticAssert !== false) {
    const layout = computeLayout(design);
    out.push(
      `_Static_assert(sizeof(${design.name}) == ${layout.size}, "${design.name} layout drift");`,
    );
    out.push('');
  }

  out.push(`#endif /* ${guard} */`);
  out.push('');

  return {
    header: out.join('\n'),
    layoutDoc: emitLayoutDoc(design, { sourceFileName: src }),
    warnings,
  };
}

// ---------------------------------------------------------------------------

function emitStructBody(
  design: Design,
  fields: Field[],
  tag: string,
  opts: HeaderOptions,
  warnings: string[],
  preludes: string[],
): string[] {
  const layout: LayoutResult = layoutFieldList(design, fields, tag);
  const specs: Array<{ type: string; decl: string; comment?: string }> = [];

  fields.forEach((field, i) => {
    const row = layout.rows[i];
    /** decorate a member comment with a "reserved" tag when appropriate */
    const rsv = (c?: string): string | undefined => {
      if (!field.reserved) {
        return c;
      }
      if (c && /reserved/i.test(c)) {
        return c;
      }
      return c ? `reserved — ${c}` : 'reserved — do not use';
    };

    // ---- enum prelude ----
    if (field.enum && !field.bits) {
      preludes.push(emitEnum(tag, field));
    }

    // ---- bitfield prelude + member ----
    if (field.bits && field.bits.length > 0) {
      const bitTag = `${tag}_${field.name}`;
      preludes.push(emitBitStruct(bitTag, field));
      specs.push({ type: bitTag, decl: `${field.name}${row.cArraySuffix};`, comment: rsv(field.description) });
      return;
    }

    // ---- inline struct prelude + member ----
    if (field.type === 'struct' || parseBase(field.type) === 'struct') {
      const inlineTag = `${tag}_${field.name}`;
      const innerPreludes: string[] = [];
      const innerBody = emitStructBody(design, field.fields ?? [], inlineTag, opts, warnings, innerPreludes);
      for (const p of innerPreludes) {
        preludes.push(p);
      }
      preludes.push(
        `typedef struct ${inlineTag} {\n${innerBody.join('\n')}\n} ${inlineTag};`,
      );
      specs.push({ type: inlineTag, decl: `${field.name}${row.cArraySuffix};`, comment: rsv(field.description) });
      return;
    }

    // ---- array.countField member ----
    if (field.array?.countField) {
      const isLast = i === fields.length - 1;
      const elemType = row.cType;
      if (opts.arrayMax && opts.arrayMax > 0) {
        specs.push({
          type: elemType,
          decl: `${field.name}[${opts.arrayMax}];`,
          comment: rsv(`count = ${field.array.countField}, capacity ${opts.arrayMax}`),
        });
      } else if (isLast) {
        specs.push({
          type: elemType,
          decl: `${field.name}[];`,
          comment: rsv(`flexible array member; count = ${field.array.countField}`),
        });
      } else {
        warnings.push(
          `field "${field.name}" uses array.countField but no header arrayMax was given and it is not the last member; emitted [1]`,
        );
        specs.push({
          type: elemType,
          decl: `${field.name}[1];`,
          comment: rsv(`count = ${field.array.countField}; set binaryDesigner.header.arrayMax`),
        });
      }
      return;
    }

    // ---- plain member ----
    let type = row.cType;
    if (field.enum && opts.enumTypedefForFields) {
      type = `${tag}_${field.name}`;
    }
    specs.push({
      type,
      decl: `${field.name}${row.cArraySuffix};`,
      comment: rsv(field.description),
    });
  });

  // align the declaration column, and the trailing-comment column
  const typeWidth = specs.reduce((w, s) => Math.max(w, s.type.length), 0);
  const declWidth = specs.reduce((w, s) => Math.max(w, s.decl.length), 0);
  return specs.map((s) => {
    const typePad = ' '.repeat(typeWidth - s.type.length + 1);
    let line = `    ${s.type}${typePad}${s.decl}`;
    if (s.comment) {
      line += `${' '.repeat(declWidth - s.decl.length + 2)}/* ${s.comment} */`;
    }
    return line;
  });
}

function emitEnum(tag: string, field: Field): string {
  const enumTag = `${tag}_${field.name}`;
  const prefix = `${toUpperSnake(tag)}_${toUpperSnake(field.name)}`;
  const entries = Object.entries(field.enum!)
    .map(([k, label]) => ({ k: Number(k), label }))
    .sort((a, b) => a.k - b.k);
  const width = entries.reduce((w, e) => Math.max(w, e.label.length), 0);
  const lines = entries.map((e, i) => {
    const name = `${prefix}_${toUpperSnake(e.label)}`;
    const pad = ' '.repeat(Math.max(0, width - e.label.length));
    const comma = i === entries.length - 1 ? '' : ',';
    return `    ${name}${pad} = ${e.k}${comma}`;
  });
  return `typedef enum ${enumTag} {\n${lines.join('\n')}\n} ${enumTag};`;
}

function emitBitStruct(bitTag: string, field: Field): string {
  const si = scalarInfo(parseBase(field.type));
  const cType = si ? si.cType : 'uint32_t';
  const nameWidth = (field.bits ?? []).reduce((w, b) => Math.max(w, b.name.length), 0);
  const lines = (field.bits ?? []).map((b) => {
    const pad = ' '.repeat(Math.max(0, nameWidth - b.name.length));
    const cmt = b.description ? `  /* ${b.description} */` : '';
    return `    ${cType} ${b.name}${pad} : ${b.width};${cmt}`;
  });
  return `typedef struct ${bitTag} {\n${lines.join('\n')}\n} ${bitTag};`;
}

function parseBase(type: string): string {
  try {
    return parseType(type).base;
  } catch {
    return type;
  }
}

/** Kahn topological sort of `design.structs` by struct-name references. */
export function topoSortStructs(design: Design): string[] {
  const structs = design.structs ?? {};
  const names = Object.keys(structs);
  const nameSet = new Set(names);
  const deps = new Map<string, Set<string>>();

  for (const name of names) {
    const set = new Set<string>();
    collectStructRefs(structs[name].fields, nameSet, set);
    set.delete(name);
    deps.set(name, set);
  }

  const result: string[] = [];
  const done = new Set<string>();
  let progressed = true;
  while (result.length < names.length && progressed) {
    progressed = false;
    for (const name of names) {
      if (done.has(name)) {
        continue;
      }
      const remaining = [...(deps.get(name) ?? [])].filter((d) => !done.has(d));
      if (remaining.length === 0) {
        result.push(name);
        done.add(name);
        progressed = true;
      }
    }
  }
  // cycle fallback: append the rest in declaration order
  for (const name of names) {
    if (!done.has(name)) {
      result.push(name);
    }
  }
  return result;
}

function collectStructRefs(fields: Field[], nameSet: Set<string>, into: Set<string>): void {
  for (const f of fields) {
    const base = parseBase(f.type);
    if (nameSet.has(base)) {
      into.add(base);
    }
    if (f.fields) {
      collectStructRefs(f.fields, nameSet, into);
    }
    if (f.items) {
      collectStructRefs([f.items], nameSet, into);
    }
  }
}

export { sanitizeIdentifier };
