/**
 * Markdown layout doc: `offset · name · C type · size` plus totals and padding.
 */

import { Design } from './types';
import { computeLayout } from './layout';

export interface LayoutDocOptions {
  sourceFileName?: string;
}

export function emitLayoutDoc(design: Design, opts: LayoutDocOptions = {}): string {
  const layout = computeLayout(design);
  const src = opts.sourceFileName ?? `${design.name}.design.json`;

  const lines: string[] = [];
  lines.push(`<!-- Generated by Binary File Designer — do not edit. Regenerate from ${src}. -->`);
  lines.push(`# ${design.name} — layout`);
  lines.push('');
  if (design.description) {
    lines.push(design.description);
    lines.push('');
  }
  lines.push(`- **Endianness:** ${layout.endianness}`);
  lines.push(`- **Packing:** ${layout.packing} byte(s)`);
  lines.push(`- **Total size:** ${layout.size} bytes`);
  lines.push(`- **Struct alignment:** ${layout.align}`);
  lines.push(`- **Padding inserted:** ${layout.paddingBytes} bytes`);
  lines.push('');
  lines.push('| Offset | Name | C type | Size | Align | Notes |');
  lines.push('| -----: | ---- | ------ | ---: | ----: | ----- |');

  let cursor = 0;
  for (const row of layout.rows) {
    if (row.offset > cursor) {
      lines.push(
        `| ${cursor} | *(padding)* | \`uint8_t[${row.offset - cursor}]\` | ${row.offset - cursor} | 1 | inserted by packer |`,
      );
    }
    const cType = `${row.cType}${row.cArraySuffix}`;
    lines.push(
      `| ${row.offset} | \`${row.name}\` | \`${cType}\` | ${row.size} | ${row.align} | ${row.note ?? ''} |`,
    );
    cursor = row.offset + row.size;
  }
  if (layout.size > cursor) {
    lines.push(
      `| ${cursor} | *(tail padding)* | \`uint8_t[${layout.size - cursor}]\` | ${layout.size - cursor} | 1 | struct size rounded to alignment |`,
    );
  }
  lines.push('');
  lines.push(`_Total: **${layout.size} bytes**._`);
  lines.push('');
  return lines.join('\n');
}
